version: '3'

services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    restart: on-failure
    networks:
      - docker_network
    expose:
      - 3306
    volumes:
      - mariadb:/var/lib/mysql
    env_file: .env
  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
    restart: on-failure
    networks:
      - docker_network
    depends_on:
      - mariadb
    expose:
      - 9000
    volumes:
      - wordpress:/var/www/html/wordpress
    env_file: .env
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    restart: on-failure
    networks:
      - docker_network
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - wordpress
    env_file: .env

networks:
  docker_network:
    name: docker_network
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/tedelin/data/mariadb'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/tedelin/data/wordpress'
