services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    restart: unless-stopped
    networks:
      - inception_network
    expose:
      - 3306
    volumes:
      - database:/var/lib/mysql
    env_file: .env
  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
    restart: unless-stopped
    networks:
      - inception_network
    depends_on:
      - mariadb
    expose:
      - 9000
    volumes:
      - website:/var/www/html/wordpress
    env_file: .env
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    restart: unless-stopped
    networks:
      - inception_network
    ports:
      - 443:443
    volumes:
      - website:/var/www/html/wordpress
    depends_on:
      - wordpress
    env_file: .env
networks:
  inception_network:
    name: inception_network
    driver: bridge

volumes:
  database:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${HOME}/data/mariadb"
  website:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${HOME}/data/wordpress"
