services:
  nginx:
    build:
      context: requirements/nginx
    restart: always
    networks:
      - wp_network
    ports:
      - 443:443
    volumes:
      - wp_data:/var/www/html:ro
    env_file:
      .env
    
  wordpress:
    build:
      context: requirements/wordpress
    restart: always
    networks:
      - db_network
      - wp_network
    expose:
      - 9000
    volumes:
      - wp_data:/var/www/html
    env_file:
      .env

  mariadb:
    build:
      context: requirements/mariadb
    restart: always
    networks:
      - db_network
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      .env


networks:
  wp_network:
    driver: bridge
  db_network:
    driver: bridge


volumes:
  db_data:
  wp_data: